# Vamos a mencionar la versiòn del Docker Compose con la que vamos a trabajar
version: '3'

# Indicamos los servicios que vamos a implementar
services:
  angularApp:
    build:
      # Lo que vamos a construir
      context: . #El punto va a hacer referencia al proyecto que tenemos
      dockerfile: docker-angular/Dockerfile # Especificamos la ubicaón del archivo que queremos leer
    restart: always # Para que se levante el servidor en el caso de que se caiga
    #image: docker-angular # El nombre que le vamos a dar a la imagen
    ports:
      - '127.0.0.1:4000:80' # El puerto en el que queremos que corra la app

  json-server:
    build:
      context: .
      dockerfile: docker-json/Dockerfile
    restart: always
    #image: docker-json
    ports:
      - '3000:3000'
